name: 'client-pr'
on:
  pull_request:
    branches: [main]
    paths:
      - 'holo-key-manager-js-client/package.json'
      - '.github/workflows/client-PR.yaml'
  merge_group:
    branches: [main]
    types: [checks_requested]

jobs:
  build:
    name: 'PR Client Build and Test'
    runs-on: ubuntu-latest

    environment:
      name: Client

    steps:
      - uses: actions/checkout@v4
      - name: Setup Node.js environment
        uses: actions/setup-node@v4
        with:
          node-version: lts/*
          registry-url: 'https://registry.npmjs.org'
      - name: Install pnpm
        run: npm install -g pnpm
      - name: Install dependencies
        run: pnpm install --no-frozen-lockfile
        working-directory: holo-key-manager-js-client
      - name: Run unit tests
        run: pnpm test
        working-directory: holo-key-manager-js-client
