name: 'test'
on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    environment:
      name: test

    steps:
      - uses: actions/checkout@v4

      - name: Setup Node.js environment
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install pnpm
        run: npm install -g pnpm

      - name: Install dependencies
        run: pnpm install

      - name: Build extension
        run: pnpm run build

      - name: Zip the build
        run: |
          cd build
          zip -r ../build.zip .
          cd ..

      - name: Chrome upload & release
        uses: mnao305/chrome-extension-upload@v4.0.1
        with:
          file-path: build.zip
          extension-id: eggfhkdnfdhdpmkfpihjjbnncgmhihce
          client-id: ${{ secrets.CHROME_CLIENT_ID }}
          client-secret: ${{ secrets.CHROME_CLIENT_SECRET }}
          refresh-token: ${{ secrets.CHROME_REFRESH_TOKEN }}

      - name: Edge upload & release
        uses: inverse/edge-addon@v1.0.9
        with:
          product_id: 70d8655d-2c91-4b81-99b1-35afa863ea8c
          zip: build.zip
          client_id: ${{ secrets.EDGE_CLIENT_ID }}
          client_secret: ${{ secrets.EDGE_CLIENT_SECRET }}
          access_token_url: ${{ secrets.EDGE_ACCESS_TOKEN_URL }}