name: 'test'
on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    environment:
      name: test

    steps:
      - uses: actions/checkout@v4

      - name: Setup Node.js environment
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install pnpm
        run: npm install -g pnpm

      - name: Install dependencies
        run: pnpm install

      - name: Build extension
        run: pnpm run build

      - name: Zip the build
        run: |
          cd build
          zip -r ../build.zip .
          cd ..

      - name: Chrome upload & release
        uses: mnao305/chrome-extension-upload@v4.0.1
        with:
          file-path: build.zip
          extension-id: eggfhkdnfdhdpmkfpihjjbnncgmhihce
          client-id: ${{ secrets.CHROME_CLIENT_ID }}
          client-secret: ${{ secrets.CHROME_CLIENT_SECRET }}
          refresh-token: ${{ secrets.CHROME_REFRESH_TOKEN }}
        continue-on-error: true

      # - name: Chrome upload & release
      #   uses: Klemensas/chrome-extension-upload-action@$VERSION
      #   with:
      #     refresh-token: 'xxxxxxxxxxxxxxxxxxxxxx'
      #     client-id: 'xxxxxxxxxxxxx'
      #     client-secret: 'xxxxxxxxxxxx'
      #     file-name: './extension.zip'
      #     app-id: 'xzc12xzc21cx23'
      #     publish: true

      - name: Edge upload & release
        uses: wdzeng/edge-addon@v1.2.1
        with:
          product-id: 70d8655d-2c91-4b81-99b1-35afa863ea8c
          zip-path: build.zip
          client-id: ${{ secrets.EDGE_CLIENT_ID }}
          client-secret: ${{ secrets.EDGE_CLIENT_SECRET }}
          access-token-url: ${{ secrets.EDGE_ACCESS_TOKEN_URL }}
