name: 'test'
on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    environment:
      name: test

    steps:
      - uses: actions/checkout@v4

      - name: Setup Node.js environment
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install pnpm
        run: npm install -g pnpm

      - name: Install dependencies
        run: pnpm install

      - name: Build extension
        run: pnpm build

      - name: Zip the build
        run: |
          cd build
          zip -r ../build.zip .
          cd ..

      - name: Chrome upload & release
        uses: mobilefirstllc/cws-publish@latest
        continue-on-error: true
        with:
          action: publish
          client_id: ${{ secrets.CHROME_CLIENT_ID }}
          client_secret: ${{ secrets.CHROME_CLIENT_SECRET }}
          refresh_token: ${{ secrets.CHROME_REFRESH_TOKEN }}
          extension_id: ${{ vars.CHROME_ID }}
          zip_file: build.zip

      - name: Edge upload & release
        uses: wdzeng/edge-addon@v1.2.1
        with:
          product-id: ${{ vars.EDGE_ID }}
          zip-path: build.zip
          client-id: ${{ secrets.EDGE_CLIENT_ID }}
          client-secret: ${{ secrets.EDGE_CLIENT_SECRET }}
          access-token-url: ${{ secrets.EDGE_ACCESS_TOKEN_URL }}

      - name: Replace manifest
        run: pnpm build:replaceForFirefox ${{ vars.FF_ID }}

      - name: Build extension
        run: pnpm build

      - name: Zip the build
        run: |
          cd build
          zip -r ../buildFF.zip .
          cd ..

      - name: Firefox upload & release
        uses: cardinalby/webext-buildtools-firefox-addons-action@1.0.9
        with:
          zipFilePath: buildFF.zip
          extensionId: ${{ vars.FF_ID }}
          jwtIssuer: ${{ secrets.FF_JWT_ISSUER }}
          jwtSecret: ${{ secrets.FF_JWT_SECRET }}
