name: 'test'
on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    environment:
      name: test

    steps:
      - uses: actions/checkout@v4
      - name: Setup Node.js environment
        uses: actions/setup-node@v3
        with:
          node-version: 18
      - name: Install axios
        run: npm install axios
      - name: Check version against latest release in Chrome Web Store
        id: check_version
        uses: actions/github-script@v6
        with:
          script: |
            const fs = require('fs/promises');
            const axios = require('axios');
            const fetchVersionInfo = async () => {
              try {
                const data = await fs.readFile('./static/manifest.json', 'utf8');
                console.log('Read file data:', data);
                const manifest = JSON.parse(data);
                console.log('Parsed manifest:', manifest);
                const currentVersion = manifest.version;
                console.log('Current version:', currentVersion);
                const response = await axios.get(`https://chromewebstore.google.com/detail/holo-key-manager/${{ vars.CHROME_ID}}`, { maxRedirects: 10 });
                const text = response.data;
                console.log('Response text:', text);
                const versionPattern = /<div[^>]*>Version<\/div><div[^>]*>(\d+\.\d+\.\d+)<\/div>/;
                console.log('Version pattern:', versionPattern);
                const versionMatch = text.match(versionPattern);
                console.log('Version match:', versionMatch);
                const latestVersion = versionMatch ? versionMatch[1] : null;
                console.log('Latest version:', latestVersion);
                core.setOutput('abort', currentVersion === latestVersion ? 'true' : 'false');
              } catch (error) {
                core.setFailed(error.message);
              }
            };
            fetchVersionInfo();
      - name: Abort build if version matches
        if: steps.check_version.outputs.abort == 'true'
        run: |
          echo "Version in manifest matches the latest release version in Chrome Web Store. Aborting build."
          exit 1
      - name: Install pnpm
        run: npm install -g pnpm

      - name: Install dependencies
        run: pnpm install

      - name: Build extension
        run: pnpm build

      - name: Zip the build
        run: |
          cd build
          zip -r ../build.zip .
          cd ..

      - name: Chrome upload & release
        uses: mobilefirstllc/cws-publish@latest
        continue-on-error: true
        with:
          action: publish
          client_id: ${{ secrets.CHROME_CLIENT_ID }}
          client_secret: ${{ secrets.CHROME_CLIENT_SECRET }}
          refresh_token: ${{ secrets.CHROME_REFRESH_TOKEN }}
          extension_id: ${{ vars.CHROME_ID }}
          zip_file: build.zip

      - name: Edge upload & release
        uses: wdzeng/edge-addon@v1.2.1
        continue-on-error: true
        with:
          product-id: ${{ vars.EDGE_ID }}
          zip-path: build.zip
          client-id: ${{ secrets.EDGE_CLIENT_ID }}
          client-secret: ${{ secrets.EDGE_CLIENT_SECRET }}
          access-token-url: ${{ secrets.EDGE_ACCESS_TOKEN_URL }}

      - name: Replace manifest
        run: pnpm build:replaceForFirefox ${{ vars.FF_ID }}

      - name: Build extension
        run: pnpm build

      - name: Zip the build
        run: |
          cd build
          zip -r ../buildFF.zip .
          cd ..

      - name: Firefox upload & release
        uses: cardinalby/webext-buildtools-firefox-addons-action@1.0.9
        with:
          zipFilePath: buildFF.zip
          extensionId: ${{ vars.FF_ID }}
          jwtIssuer: ${{ secrets.FF_JWT_ISSUER }}
          jwtSecret: ${{ secrets.FF_JWT_SECRET }}
